[versions]
# Minecraft
paper = "1.21-R0.1-SNAPSHOT"
minecraft = "1.21"

# Plugins
itemsadder = "3.6.3-beta-14"
headdatabaseapi = "1.3.1"
placeholderapi = "2.11.6"
decentholograms = "2.8.8"
fancyholograms = "2.2.0"
worldguard = "7.0.10"
oraxen = "1.171.0"
nbtapi = "2.13.1-SNAPSHOT"
vault = "1.7.1"

# Libraries
triumph-cmd = "2.0.0-ALPHA-10"
tirumph-gui = "3.1.7"
jetbrains = "24.1.0"
kyori = "4.17.0"
vital = "1.5.9"

# Paper
paperweight="1.7.1"
runPaper = "2.3.0"
hangar = "0.1.2"

# Other
shadowJar = "8.1.7"

# Modrinth
minotaur = "2.+"

[plugins]
paperweight = { id = "io.papermc.paperweight.userdev", version.ref = "paperweight" }
hangar = { id = "io.papermc.hangar-publish-plugin", version.ref = "hangar" }
shadowJar = { id = "io.github.goooler.shadow", version.ref = "shadowJar" }
runPaper = { id = "xyz.jpenilla.run-paper", version.ref = "runPaper" }
minotaur = { id = "com.modrinth.minotaur", version.ref = "minotaur" }

[libraries]
oraxen-api = { group = "io.th0rgal", name = "oraxen", version = "1.171.0" }
placeholder-api = { group = "me.clip", name = "placeholderapi", version = "2.11.5" }

worldedit = { group = "com.sk89q.worldedit", name = "worldedit-bukkit", version = "7.2.15" }
worldguard = { group = "com.sk89q.worldguard", name = "worldguard-bukkit", version = "7.1.0-SNAPSHOT" }

nbtapi = { group = "de.tr7zw", name = "item-nbt-api", version = "2.13.1-SNAPSHOT" }

triumph-cmds = { group = "dev.triumphteam", name = "triumph-cmd-bukkit", version = "2.0.0-ALPHA-9" }
triumph-gui = { group = "dev.triumphteam", name = "triumph-gui", version = "3.1.7" }

vault = { group = "com.github.MilkBowl", name = "VaultAPI", version = "1.7.1" }
metrics = { group = "org.bstats", name = "bstats-bukkit", version = "3.0.2" }
config-me = { group = "ch.jalu", name = "configme", version = "1.4.1" }

griefprevention = { group = "com.github.TechFortress", name = "GriefPrevention", version = "16.18.2" }
towny = { group = "com.palmergames.bukkit.towny", name = "towny", version = "0.100.2.0" }
factions = { group = "com.massivecraft", name = "Factions", version = "1.6.9.5-U0.6.31" }

skyblock = { group = "com.bgsoftware", name = "SuperiorSkyblockAPI", version = "2023.2" }
plotsquared = { group = "com.plotsquared", name = "PlotSquared-Core", version = "6.11.1" }
mcmmo = { group = "com.gmail.nossr50.mcMMO", name = "mcMMO", version = "2.2.0-SNAPSHOT" } # https://repo.codemc.io/service/rest/repository/browse/maven-public/com/gmail/nossr50/mcMMO/mcMMO/
wildstacker = { group = "com.bgsoftware", name = "WildStackerAPI", version = "2023.2" }

kingdoms = { group = "com.github.cryptomorin", name = "kingdoms", version = "1.16.20.5"}

informative-annotations = { group = "com.intellectualsites.informative-annotations", name = "informative-annotations", version = "1.3" }
paster = { group = "com.intellectualsites.paster", name = "Paster", version = "1.1.5" }

nocheatplus = { group = "fr.neatmonster", name = "nocheatplus", version = "3.16.1-SNAPSHOT" }

[bundles]
triumph = ["triumph-cmds", "triumph-gui"]