[plugins]
paperweight = { id = "io.papermc.paperweight.userdev", version.ref = "paperweight" }
hangar = { id = "io.papermc.hangar-publish-plugin", version.ref = "hangar" }
runPaper = { id = "xyz.jpenilla.run-paper", version.ref = "runPaper" }
minotaur = { id = "com.modrinth.minotaur", version.ref = "minotaur" }
shadow = { id = "com.gradleup.shadow", version.ref = "shadow" }

[versions]
# Minecraft
paper = "1.21.1-R0.1-SNAPSHOT"
minecraft = "1.21.1"

# Plugins
headdatabaseapi = "1.3.1"        # Not Used
placeholderapi = "2.11.6"        # https://github.com/PlaceholderAPI/PlaceholderAPI/wiki/Hook-into-PlaceholderAPI
worldguard = "7.0.10"            # https://dev.bukkit.org/projects/worldguard/files
worldedit = "7.3.6"              # https://modrinth.com/plugin/worldedit/versions?l=bukkit
oraxen = "1.181.0"               # https://github.com/oraxen/oraxen#api
vault = "1.7.1"                  # Never Updates: https://github.com/milkbowl/Vault
griefprevention = "17.0.0"       # https://jitpack.io/#GriefPrevention/GriefPrevention
towny = "0.100.3.0"              # https://github.com/TownyAdvanced/Towny?tab=readme-ov-file#current-recommended-versions
factions = "1.6.9.5-U0.6.40"     # https://www.spigotmc.org/resources/factionsuuid.1035/
lands = "7.8.10"                 # https://github.com/Angeschossen/LandsAPI/wiki
skyblock = "2024.3"              # https://bg-software.com/superiorskyblock/
plotsquared = "7.3.10"           # https://intellectualsites.gitbook.io/plotsquared/api/api-documentation
mcmmo = "2.1.227"                # https://repo.codemc.io/service/rest/repository/browse/maven-public/com/gmail/nossr50/mcMMO/mcMMO/
kingdoms = "1.16.20.5"           # https://www.spigotmc.org/resources/kingdomsx.77670/

# AniCheat
nocheatsplus = "3.16.1-SNAPSHOT" # https://ci.codemc.io/job/Updated-NoCheatPlus/

# Libraries
triumph-cmd = "2.0.0-ALPHA-10"   # Version=MIA https://github.com/TriumphTeam/triumph-cmds?tab=readme-ov-file
tirumph-gui = "3.1.10"           # https://mvnrepository.com/artifact/dev.triumphteam/triumph-gui
config-me = "1.4.1"              # https://mvnrepository.com/artifact/ch.jalu/configme
jetbrains = "24.1.0"             # Not Used
kyori = "4.17.0"                 # Not Used
vital = "1.5.9"                  # Not Used
metrics = "3.0.3"                # https://mvnrepository.com/artifact/org.bstats/bstats-bukkit

# Paper
paperweight = "1.7.2"            # https://plugins.gradle.org/plugin/io.papermc.paperweight.userdev
runPaper = "2.3.1"               # https://plugins.gradle.org/plugin/xyz.jpenilla.run-paper
hangar = "0.1.2"                 # https://plugins.gradle.org/plugin/io.papermc.hangar-publish-plugin

# Other
shadow = "8.3.0"                 # https://gradleup.com/shadow/

# Modrinth
minotaur = "2.8.7"               # https://plugins.gradle.org/plugin/com.modrinth.minotaur

[libraries]
oraxen = { module = "io.th0rgal:oraxen", version.ref = "oraxen" }
placeholderapi = { module = "me.clip:placeholderapi", version.ref = "placeholderapi" }

worldedit = { module = "com.sk89q.worldedit:worldedit-bukkit", version.ref = "worldedit" }
worldguard = { module = "com.sk89q.worldguard:worldguard-bukkit", version.ref = "worldguard" }

triumph-cmds = { module = "dev.triumphteam:triumph-cmd-bukkit", version.ref = "triumph-cmd" }
triumph-gui = { module = "dev.triumphteam:triumph-gui", version.ref = "tirumph-gui" }

vault = { module = "com.github.MilkBowl:VaultAPI", version.ref = "vault" }
metrics = { module = "org.bstats:bstats-bukkit", version.ref = "metrics" }
config-me = { module = "ch.jalu:configme", version.ref = "config-me" }

griefprevention = { module = "com.github.GriefPrevention:GriefPrevention", version.ref = "griefprevention" }
towny = { module = "com.palmergames.bukkit.towny:towny", version.ref = "towny" }
factions = { module = "com.massivecraft:Factions", version.ref = "factions" }
lands = { module = "com.github.Angeschossen:LandsAPI", version.ref = "lands" }

skyblock = { module = "com.bgsoftware:SuperiorSkyblockAPI", version.ref = "skyblock" }
plotsquared = { module = "com.intellectualsites.plotsquared:plotsquared-core", version.ref = "plotsquared" }
mcmmo = { module = "com.gmail.nossr50.mcMMO:mcMMO", version.ref = "mcmmo" }

kingdoms = { module = "com.github.cryptomorin:kingdoms", version.ref = "kingdoms"}

informative-annotations = { group = "com.intellectualsites.informative-annotations", name = "informative-annotations", version = "1.5" } #https://central.sonatype.com/artifact/com.intellectualsites.informative-annotations/informative-annotations
paster = { group = "com.intellectualsites.paster", name = "Paster", version = "1.1.6" } #https://mvnrepository.com/artifact/com.intellectualsites.paster

nocheatplus = { module = "fr.neatmonster:nocheatplus", version.ref = "nocheatsplus" }

[bundles]
triumph = ["triumph-cmds", "triumph-gui"]