[versions]
# Minecraft
paper = "1.21-R0.1-SNAPSHOT"
minecraft = "1.21"

# Plugins
itemsadder = "3.6.3-beta-14"
headdatabaseapi = "1.3.1"
placeholderapi = "2.11.6"
decentholograms = "2.8.8"
fancyholograms = "2.2.0"
worldguard = "7.0.10"
worldedit = "7.2.15"
oraxen = "1.171.0"
nbtapi = "2.13.1-SNAPSHOT"
vault = "1.7.1"
griefprevention = "16.18.2"
towny = "0.100.2.0"
factions = "1.6.9.5-U0.6.31"
skyblock = "2023.2"
plotsquared = "6.11.1"
mcmmo = "2.2.0-SNAPSHOT"
wildstacker = "2023.2"
kingdoms = "1.16.20.5"

# AniCheat
nocheatsplus = "3.16.1-SNAPSHOT"

# Libraries
triumph-cmd = "2.0.0-ALPHA-10"
tirumph-gui = "3.1.7"
config-me = "1.4.1"
jetbrains = "24.1.0"
kyori = "4.17.0"
vital = "1.5.9"
metrics = "3.0.2"

# Paper
paperweight="1.7.1"
runPaper = "2.3.0"
hangar = "0.1.2"

# Other
shadowJar = "8.1.7"

# Modrinth
minotaur = "2.+"

[plugins]
paperweight = { id = "io.papermc.paperweight.userdev", version.ref = "paperweight" }
hangar = { id = "io.papermc.hangar-publish-plugin", version.ref = "hangar" }
shadowJar = { id = "io.github.goooler.shadow", version.ref = "shadowJar" }
runPaper = { id = "xyz.jpenilla.run-paper", version.ref = "runPaper" }
minotaur = { id = "com.modrinth.minotaur", version.ref = "minotaur" }

[libraries]
oraxen = { module = "io.th0rgal:oraxen", version.ref = "oraxen" }
placeholderapi = { module = "me.clip:placeholderapi", version.ref = "placeholderapi" }

worldedit = { module = "com.sk89q.worldedit:worldedit-bukkit", version.ref = "worldedit" }
worldguard = { module = "com.sk89q.worldguard:worldguard-bukkit", version.ref = "worldguard" }

nbtapi = { module = "de.tr7zw:item-nbt-api", version.ref = "nbtapi" }

triumph-cmds = { module = "dev.triumphteam:triumph-cmd-bukkit", version.ref = "triumph-cmd" }
triumph-gui = { module = "dev.triumphteam:triumph-gui", version.ref = "tirumph-gui" }

vault = { module = "com.github.MilkBowl:VaultAPI", version.ref = "vault" }
metrics = { module = "org.bstats:bstats-bukkit", version.ref = "metrics" }
config-me = { module = "ch.jalu:configme", version.ref = "config-me" }

griefprevention = { module = "com.github.TechFortress:GriefPrevention", version.ref = "griefprevention" }
towny = { module = "com.palmergames.bukkit.towny:towny", version.ref = "towny" }
factions = { module = "com.massivecraft:Factions", version.ref = "factions" }

skyblock = { module = "com.bgsoftware:SuperiorSkyblockAPI", version.ref = "skyblock" }
plotsquared = { module = "com.plotsquared:PlotSquared-Core", version.ref = "plotsquared" }
mcmmo = { module = "com.gmail.nossr50.mcMMO:mcMMO", version.ref = "mcmmo" } # https://repo.codemc.io/service/rest/repository/browse/maven-public/com/gmail/nossr50/mcMMO/mcMMO/
wildstacker = { module = "com.bgsoftware:WildStackerAPI", version.ref = "wildstacker" }

kingdoms = { module = "com.github.cryptomorin:kingdoms", version.ref = "kingdoms"}

informative-annotations = { group = "com.intellectualsites.informative-annotations", name = "informative-annotations", version = "1.3" }
paster = { group = "com.intellectualsites.paster", name = "Paster", version = "1.1.5" }

nocheatplus = { module = "fr.neatmonster:nocheatplus", version.ref = "nocheatsplus" }

[bundles]
triumph = ["triumph-cmds", "triumph-gui"]