[plugins]
run-paper = { id = "xyz.jpenilla.run-paper", version = "2.2.4" }

[versions]

[libraries]
oraxen-api = { group = "io.th0rgal", name = "oraxen", version = "1.171.0" }
placeholder-api = { group = "me.clip", name = "placeholderapi", version = "2.11.5" }

worldedit = { group = "com.sk89q.worldedit", name = "worldedit-bukkit", version = "7.2.15" }
worldguard = { group = "com.sk89q.worldguard", name = "worldguard-bukkit", version = "7.1.0-SNAPSHOT" }

nbtapi = { group = "de.tr7zw", name = "item-nbt-api", version = "2.13.0" }

triumph-cmds = { group = "dev.triumphteam", name = "triumph-cmd-bukkit", version = "2.0.0-ALPHA-9" }
triumph-gui = { group = "dev.triumphteam", name = "triumph-gui", version = "3.1.7" }

vault = { group = "com.github.MilkBowl", name = "VaultAPI", version = "1.7.1" }
metrics = { group = "org.bstats", name = "bstats-bukkit", version = "3.0.2" }
config-me = { group = "ch.jalu", name = "configme", version = "1.4.1" }

griefprevention = { group = "com.github.TechFortress", name = "GriefPrevention", version = "16.18.2" }
towny = { group = "com.palmergames.bukkit.towny", name = "towny", version = "0.100.2.0" }
factions = { group = "com.massivecraft", name = "Factions", version = "1.6.9.5-U0.6.31" }

skyblock = { group = "com.bgsoftware", name = "SuperiorSkyblockAPI", version = "2023.2" }
plotsquared = { group = "com.plotsquared", name = "PlotSquared-Core", version = "6.11.1" }
mcmmo = { group = "com.gmail.nossr50.mcMMO", name = "mcMMO", version = "2.2.0-SNAPSHOT" } # https://repo.codemc.io/service/rest/repository/browse/maven-public/com/gmail/nossr50/mcMMO/mcMMO/
wildstacker = { group = "com.bgsoftware", name = "WildStackerAPI", version = "2023.2" }

kingdoms = { group = "com.github.cryptomorin", name = "kingdoms", version = "1.16.20.5"}

informative-annotations = { group = "com.intellectualsites.informative-annotations", name = "informative-annotations", version = "1.3" }
paster = { group = "com.intellectualsites.paster", name = "Paster", version = "1.1.5" }

nocheatplus = { group = "fr.neatmonster", name = "nocheatplus", version = "3.16.1-SNAPSHOT" }

[bundles]
triumph = ["triumph-cmds", "triumph-gui"]