name: "CrazyEnchantments"

main: "${group}.CrazyEnchantments"

authors: [BadBones69, RyderBelserion]

version: ${version}
api-version: "1.17"
description: ${description}
website: ${website}

softdepend:
  - WorldGuard
  - WorldEdit
  - PlotSquared
  - SuperiorSkyBlock
  - GriefPrevention
  - Spartan
  - Towny
  - Factions
  - StackMob
  - SilkSpawners
  - Vault
  - Oraxen

commands:
  crazyenchantments:
    description: Opens the Enchanter GUI.
    aliases: [ ce, enchanter ]
  tinkerer:
    description: Opens the Tinker GUI.
    aliases: tinker
  blacksmith:
    description: Opens the Black Smith GUI.
    aliases: [ bsmith, blacks, bs ]
  gkit:
    description: Opens the GKitz GUI.
    aliases: [ gkitz, gkits ]