Settings:
  EnchantmentOptions: #Options for enchanted books.
    Armor-Upgrade: #Having this enabled will allow players to try and add a higher level of an enchantment onto an item with a lower level of the enchantment.
      Toggle: true #Toggle on or off the ability to upgrade the enchantments.
      Enchantment-Break: true #If the book's destroy rate happens the item doesn't break but instead the current lower version of the enchantment is destroyed. If false then the item will be destroyed instead.
    Wings: #Options for the Wings Enchantment.
      Clouds: true #Toggle if the wings enchantment shows particles under the player's feet. Warning this option has been known to cause lag so toggle it off if you get lag.
      Enemy-Toggle: true #This toggles on and off the wings enchantment when an enemy is close to the player.
      Distance: 25 #How far away the enemy has to be to toggle off the enchantment.
      Members-Can-Fly: true #Toggle if a player is a member of a world guard region if they can fly.
      Owners-Can-Fly: true #Toggle if a player is an owner of a world guard region if they can fly.
      Regions: #All world guard regions the Wings enchantment can work in.
        - 'Free_Fly'
        - 'SafeZone'
      Worlds: #The option to disable/enable wings in worlds.
        Limitless-Flight-Worlds: #Worlds that players are allowed to fly for a limitless amount of time. This bypasses enemy checks as well.
          - 'Hub_Example'
        Whitelisted: #If the player has wings enchantment in these worlds they will be able to fly anywhere regardless of regions/enemies.
          - 'Hub_Example'
        Blacklisted: #Wings will not work at all in these worlds regardless of regions.
          - 'SkyBlock_Example'
  Costs: #This is where you set the cost of stuff in the shop GUI.
    Scrambler: #The item that is being bought.
      Cost: 800 #How much the item will cost.
      Currency: Vault #The currency that will be taken when bought.
    ProtectionCrystal:
      Cost: 500
      Currency: Vault
    TransmogScroll:
      Cost: 200
      Currency: Vault
    BlackScroll:
      Cost: 1000
      Currency: Vault
    WhiteScroll:
      Cost: 2000
      Currency: Vault
    SuccessDust:
      Cost: 500
      Currency: Vault
    DestroyDust:
      Cost: 500
      Currency: Vault
    Slot_Crystal:
      Cost: 500
      Currency: Vault
  SignOptions: #Options for the Signs.
    CategoryShopStyle: #What the sign will look like. The price will be determined by the category you pick
      Line1: '&b&lCrazy Enchant' #Line 1 of the sign
      Line2: '&b&lShop:' #Line 2 of the sign
      Line3: '&2&l%category%' #Line 3 of the sign
      Line4: '&c&lCost: &6&l%cost%XP' #Line 4 of the sign
      Buy-Message: '&7You have just bought an enchantment book, and it is %bookname%&7 from the %category%&7 tier.'
    ProtectionCrystalStyle:
      Line1: '&b&lCrazy Enchant'
      Line2: '&b&lShop:'
      Line3: '&5&lProtection &b&lCrystal'
      Line4: '&c&lCost: &a&l$500'
      Buy-Message: '&7You have just bought a &5&lProtection &b&lCrystal.' #Message when buying an item.
    ScramblerStyle:
      Line1: '&b&lCrazy Enchant'
      Line2: '&b&lShop:'
      Line3: '&e&lScrambler'
      Line4: '&c&lCost: &a&l$800'
      Buy-Message: '&7You have just bought a &e&lThe Grand Scrambler&7.' #Message when buying an item.
    SuccessDustStyle:
      Line1: '&b&lCrazy Enchant'
      Line2: '&b&lShop:'
      Line3: '&e&lMagical Angel Dust'
      Line4: '&c&lCost: &a&l$500'
      Buy-Message: '&7You have just bought a &aMagical Angel Dust&7.'
    DestroyDustStyle:
      Line1: '&b&lCrazy Enchant'
      Line2: '&b&lShop:'
      Line3: '&e&lMagical Fixing Dust'
      Line4: '&c&lCost: &a&l$500'
      Buy-Message: '&7You have just bought a &eMagical Fixing Dust&7.'
    BlackScrollStyle:
      Line1: '&b&lCrazy Enchant'
      Line2: '&b&lShop:'
      Line3: '&4&lBlack &8&lScrolls'
      Line4: '&c&lCost: &a&l$1000'
      Buy-Message: '&7You have just bought a &8&l&nBlack Scroll&7.'
    WhiteScrollStyle:
      Line1: '&b&lCrazy Enchant'
      Line2: '&b&lShop:'
      Line3: '&f&lWhite &b&lScrolls'
      Line4: '&c&lCost: &a&l$2000'
      Buy-Message: '&7You have just bought a &e&lWhite Scroll&7.'
    TransmogScrollStyle:
      Line1: '&b&lCrazy Enchant'
      Line2: '&b&lShop:'
      Line3: '&d&lTransmog &b&lScrolls'
      Line4: '&c&lCost: &a&l$200'
      Buy-Message: '&7You have just bought a &d&lTransmog Scroll&7.'
  #####################
  # Slot:<Slot> - The slot the item will go in.
  # Item:<Item Name> - The item that it will be. You can use meta data for the items. List of names: https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Material.html
  # Name:<Name> - The name that will go on the item.
  # Lore:<Line1>,<Line2>,<Line3>,<Line4> - The lore can use multiple lines by adding a , in-between letters. Example: "Lore:&7I am line1,&aI am line 2,&eI am line3"
  #Placeholders can be used in the name and lore and they must be lowercase.
  #Placeholders: %vault% %xp_level% %xp_total%
  #####################
  GUICustomization: #This allows you to customize unclickable items into your GUI.
    - 'Slot:1, Item:BLACK_STAINED_GLASS_PANE, Name: '
    - 'Slot:2, Item:BLACK_STAINED_GLASS_PANE, Name: '
    - 'Slot:3, Item:BLACK_STAINED_GLASS_PANE, Name: '
    - 'Slot:4, Item:BLACK_STAINED_GLASS_PANE, Name: '
    - 'Slot:5, Item:BLACK_STAINED_GLASS_PANE, Name: '
    - 'Slot:6, Item:BLACK_STAINED_GLASS_PANE, Name: '
    - 'Slot:7, Item:BLACK_STAINED_GLASS_PANE, Name: '
    - 'Slot:8, Item:BLACK_STAINED_GLASS_PANE, Name: '
    - 'Slot:9, Item:BLACK_STAINED_GLASS_PANE, Name: '
    - 'Slot:10, Item:BLACK_STAINED_GLASS_PANE, Name: '
    - 'Slot:18, Item:BLACK_STAINED_GLASS_PANE, Name: '
    - 'Slot:19, Item:BLACK_STAINED_GLASS_PANE, Name: '
    - 'Slot:27, Item:BLACK_STAINED_GLASS_PANE, Name: '
    - 'Slot:28, Item:BLACK_STAINED_GLASS_PANE, Name: '
    - 'Slot:36, Item:BLACK_STAINED_GLASS_PANE, Name: '
    - 'Slot:37, Item:BLACK_STAINED_GLASS_PANE, Name: '
    - 'Slot:45, Item:BLACK_STAINED_GLASS_PANE, Name: '
    - 'Slot:46, Item:BLACK_STAINED_GLASS_PANE, Name: '
    - 'Slot:47, Item:BLACK_STAINED_GLASS_PANE, Name: '
    - 'Slot:48, Item:BLACK_STAINED_GLASS_PANE, Name: '
    - 'Slot:49, Item:BLACK_STAINED_GLASS_PANE, Name: '
    - 'Slot:50, Item:BLACK_STAINED_GLASS_PANE, Name: '
    - 'Slot:51, Item:BLACK_STAINED_GLASS_PANE, Name: '
    - 'Slot:52, Item:BLACK_STAINED_GLASS_PANE, Name: '
    - 'Slot:53, Item:BLACK_STAINED_GLASS_PANE, Name: '
    - 'Slot:54, Item:BLACK_STAINED_GLASS_PANE, Name: '
    - 'Slot:11, Item:WHITE_STAINED_GLASS_PANE, Name: '
    - 'Slot:12, Item:WHITE_STAINED_GLASS_PANE, Name: '
    - 'Slot:13, Item:WHITE_STAINED_GLASS_PANE, Name: '
    - 'Slot:14, Item:WHITE_STAINED_GLASS_PANE, Name: '
    - 'Slot:15, Item:WHITE_STAINED_GLASS_PANE, Name: '
    - 'Slot:16, Item:WHITE_STAINED_GLASS_PANE, Name: '
    - 'Slot:17, Item:WHITE_STAINED_GLASS_PANE, Name: '
    - 'Slot:20, Item:WHITE_STAINED_GLASS_PANE, Name: '
    - 'Slot:26, Item:WHITE_STAINED_GLASS_PANE, Name: '
    - 'Slot:29, Item:WHITE_STAINED_GLASS_PANE, Name: '
    - 'Slot:35, Item:WHITE_STAINED_GLASS_PANE, Name: '
    - 'Slot:38, Item:WHITE_STAINED_GLASS_PANE, Name: '
    - 'Slot:39, Item:WHITE_STAINED_GLASS_PANE, Name: '
    - 'Slot:40, Item:WHITE_STAINED_GLASS_PANE, Name: '
    - 'Slot:41, Item:WHITE_STAINED_GLASS_PANE, Name: '
    - 'Slot:42, Item:WHITE_STAINED_GLASS_PANE, Name: '
    - 'Slot:43, Item:WHITE_STAINED_GLASS_PANE, Name: '
    - 'Slot:44, Item:WHITE_STAINED_GLASS_PANE, Name: '
Categories: #You can make as many different categories as you want
  Common: #Name of the category
    Name: '&a&l&nCommon' #Name in the GUI
    Slot: 31 #The Slot number the item will be in
    InGUI: true #Toggle if it's in the GUI or not.
    Lore: #The lore of the Item
      - '&eCost: &6&l20 &6XP Levels'
    Item: 'LIME_STAINED_GLASS_PANE' #The id for the item
    Glowing: true #If it has a glowing effect.
    Cost: 20 #How much each book will cost to buy.
    Currency: XP_Level #The currency you wish to use.
    Rarity: 1 #This allows the enchantments to be ordered with the Transmog Scrolls. The higher the number the rarer it is. Try and have each category have different rarities.
    LostBook: #Controls the Lost Book shop for this tier
      InGUI: false #If it shows in the /CE Gui
      Slot: 31 #Slot it will be in
      Item: 'BOOK' #The item that is shown in the GUI
      Glowing: false #Is it enchanted
      Name: '&8&l&nLost&c&l Tier1 &8&l&nBooks' #Name of the item
      Lore: #Lore on the item
        - '&7These are lost books that are'
        - '&7Said to be &c&lTier1 &7Enchantment books.'
        - '&7But no one has tried to clean the books yet.'
        - '&7Will you be the one to clean the books?'
        - ''
        - '&c&lCost: &6&l$1000'
      Cost: 1000
      Currency: Vault
      FireworkToggle: true #Toggle on and off if when opening a lost book a firework effect happens
      FireworkColors: 'Red, White, Blue' #The colors of the firework
      Sound-Toggle: false
      Sound: 'BLOCK_ANVIL_PLACE'
    EnchOptions: #Enchantment Options
      SuccessPercent: #The range for the success rate that the enchantment will have
        Max: 90 #The max success rate
        Min: 40 #The min success rate
      DestroyPercent: #The range for the destroy rate that the enchantment will have
        Max: 10 #The max destroy rate
        Min: 0 #The min destroy rate
      MaxLvlToggle: true #Turn on and off Max Level cap
      LvlRange: #The range of levels that can be found in the Category.
        Max: 2
        Min: 1
  Rare:
    Name: '&9&l&nRare'
    Slot: 32
    InGUI: true
    Lore:
      - '&eCost: &6&l40 &6XP Levels'
    Item: 'BLUE_STAINED_GLASS_PANE'
    Glowing: true
    Cost: 40
    Currency: XP_Level
    Rarity: 2
    LostBook:
      InGUI: false
      Slot: 32
      Item: 'BOOK'
      Glowing: false
      Name: '&8&l&nLost&c&l Tier2 &8&l&nBooks'
      Lore:
        - '&7These are lost books that are'
        - '&7Said to be &c&lTier2 &7Enchantment books.'
        - '&7But no one has tried to clean the books yet.'
        - '&7Will you be the one to clean the books?'
        - ''
        - '&c&lCost: &6&l$2000'
      Cost: 2000
      Currency: Vault
      FireworkToggle: true
      FireworkColors: 'Black, Yellow'
      Sound-Toggle: false
      Sound: 'BLOCK_ANVIL_PLACE'
    EnchOptions:
      SuccessPercent:
        Max: 70
        Min: 35
      DestroyPercent:
        Max: 25
        Min: 10
      MaxLvlToggle: true
      LvlRange:
        Max: 3
        Min: 2
  Legendary:
    Name: '&4&l&nLegendary'
    Slot: 33
    InGUI: true
    Lore:
      - '&eCost: &6&l60 &6XP Levels'
    Item: 'RED_STAINED_GLASS_PANE'
    Glowing: true
    Cost: 60
    Currency: XP_Level
    Rarity: 3
    LostBook:
      InGUI: false
      Slot: 33
      Item: 'BOOK'
      Glowing: false
      Name: '&8&l&nLost&c&l Tier3 &8&l&nBooks'
      Lore:
        - '&7These are lost books that are'
        - '&7Said to be &c&lTier3 &7Enchantment books.'
        - '&7But no one has tried to clean the books yet.'
        - '&7Will you be the one to clean the books?'
        - ''
        - '&c&lCost: &6&l$3000'
      Cost: 3000
      Currency: Vault
      FireworkToggle: true
      FireworkColors: 'White, Gray'
      Sound-Toggle: false
      Sound: 'BLOCK_ANVIL_PLACE'
    EnchOptions:
      SuccessPercent:
        Max: 50
        Min: 25
      DestroyPercent:
        Max: 35
        Min: 15
      MaxLvlToggle: true
      LvlRange:
        Max: 5
        Min: 3
  Mythical:
    Name: '&5&l&nMythical'
    Slot: 41
    InGUI: true
    Lore:
      - '&eCost: &6&l120 &6XP Levels'
    Item: 'AMETHYST_CLUSTER'
    Glowing: true
    Cost: 120
    Currency: XP_Level
    Rarity: 10
    LostBook:
      InGUI: false
      Slot: 41
      Item: 'BOOK'
      Glowing: false
      Name: '&8&l&nLost&c&l Tier 10 &8&l&nBooks'
      Lore:
        - '&7These are lost books that are'
        - '&7Said to be &c&lTier 10 &7Enchantment books.'
        - '&7But no one has tried to clean the books yet.'
        - '&7Will you be the one to clean the books?'
        - ''
        - '&c&lCost: &6&l$10000'
      Cost: 10000
      Currency: Vault
      FireworkToggle: true
      FireworkColors: 'White, Gray'
      Sound-Toggle: false
      Sound: 'BLOCK_ANVIL_PLACE'
    EnchOptions:
      SuccessPercent:
        Max: 15
        Min: 1
      DestroyPercent:
        Max: 95
        Min: 20
      MaxLvlToggle: true
      LvlRange:
        Max: 10
        Min: 1