Categories: #You can make as many different categories as you want
  Common: #Name of the category
    Name: '&a&l&nCommon' #Name in the GUI
    Slot: 31 #The Slot number the item will be in
    InGUI: true #Toggle if it's in the GUI or not.
    Lore: #The lore of the Item
      - '&eCost: &6&l20 &6XP Levels'
    Item: 'LIME_STAINED_GLASS_PANE' #The id for the item
    Glowing: true #If it has a glowing effect.
    Cost: 20 #How much each book will cost to buy.
    Currency: XP_Level #The currency you wish to use.
    Rarity: 1 #This allows the enchantments to be ordered with the Transmog Scrolls. The higher the number the rarer it is. Try and have each category have different rarities.
    LostBook: #Controls the Lost Book shop for this tier
      InGUI: false #If it shows in the /CE Gui
      Slot: 31 #Slot it will be in
      Item: 'BOOK' #The item that is shown in the GUI
      Glowing: false #Is it enchanted
      Name: '&8&l&nLost&c&l Tier1 &8&l&nBooks' #Name of the item
      Lore: #Lore on the item
        - '&7These are lost books that are'
        - '&7Said to be &c&lTier1 &7Enchantment books.'
        - '&7But no one has tried to clean the books yet.'
        - '&7Will you be the one to clean the books?'
        - ''
        - '&c&lCost: &6&l$1000'
      Cost: 1000
      Currency: Vault
      FireworkToggle: true #Toggle on and off if when opening a lost book a firework effect happens
      FireworkColors: 'Red, White, Blue' #The colors of the firework
      Sound-Toggle: false
      Sound: 'BLOCK_ANVIL_PLACE'
    EnchOptions: #Enchantment Options
      SuccessPercent: #The range for the success rate that the enchantment will have
        Max: 90 #The max success rate
        Min: 40 #The min success rate
      DestroyPercent: #The range for the destroy rate that the enchantment will have
        Max: 10 #The max destroy rate
        Min: 0 #The min destroy rate
      MaxLvlToggle: true #Turn on and off Max Level cap
      LvlRange: #The range of levels that can be found in the Category.
        Max: 2
        Min: 1
  Rare:
    Name: '&9&l&nRare'
    Slot: 32
    InGUI: true
    Lore:
      - '&eCost: &6&l40 &6XP Levels'
    Item: 'BLUE_STAINED_GLASS_PANE'
    Glowing: true
    Cost: 40
    Currency: XP_Level
    Rarity: 2
    LostBook:
      InGUI: false
      Slot: 32
      Item: 'BOOK'
      Glowing: false
      Name: '&8&l&nLost&c&l Tier2 &8&l&nBooks'
      Lore:
        - '&7These are lost books that are'
        - '&7Said to be &c&lTier2 &7Enchantment books.'
        - '&7But no one has tried to clean the books yet.'
        - '&7Will you be the one to clean the books?'
        - ''
        - '&c&lCost: &6&l$2000'
      Cost: 2000
      Currency: Vault
      FireworkToggle: true
      FireworkColors: 'Black, Yellow'
      Sound-Toggle: false
      Sound: 'BLOCK_ANVIL_PLACE'
    EnchOptions:
      SuccessPercent:
        Max: 70
        Min: 35
      DestroyPercent:
        Max: 25
        Min: 10
      MaxLvlToggle: true
      LvlRange:
        Max: 3
        Min: 2
  Legendary:
    Name: '&4&l&nLegendary'
    Slot: 33
    InGUI: true
    Lore:
      - '&eCost: &6&l60 &6XP Levels'
    Item: 'RED_STAINED_GLASS_PANE'
    Glowing: true
    Cost: 60
    Currency: XP_Level
    Rarity: 3
    LostBook:
      InGUI: false
      Slot: 33
      Item: 'BOOK'
      Glowing: false
      Name: '&8&l&nLost&c&l Tier3 &8&l&nBooks'
      Lore:
        - '&7These are lost books that are'
        - '&7Said to be &c&lTier3 &7Enchantment books.'
        - '&7But no one has tried to clean the books yet.'
        - '&7Will you be the one to clean the books?'
        - ''
        - '&c&lCost: &6&l$3000'
      Cost: 3000
      Currency: Vault
      FireworkToggle: true
      FireworkColors: 'White, Gray'
      Sound-Toggle: false
      Sound: 'BLOCK_ANVIL_PLACE'
    EnchOptions:
      SuccessPercent:
        Max: 50
        Min: 25
      DestroyPercent:
        Max: 35
        Min: 15
      MaxLvlToggle: true
      LvlRange:
        Max: 5
        Min: 3
  Mythical:
    Name: '&5&l&nMythical'
    Slot: 41
    InGUI: true
    Lore:
      - '&eCost: &6&l120 &6XP Levels'
    Item: 'AMETHYST_CLUSTER'
    Glowing: true
    Cost: 120
    Currency: XP_Level
    Rarity: 10
    LostBook:
      InGUI: false
      Slot: 41
      Item: 'BOOK'
      Glowing: false
      Name: '&8&l&nLost&c&l Tier 10 &8&l&nBooks'
      Lore:
        - '&7These are lost books that are'
        - '&7Said to be &c&lTier 10 &7Enchantment books.'
        - '&7But no one has tried to clean the books yet.'
        - '&7Will you be the one to clean the books?'
        - ''
        - '&c&lCost: &6&l$10000'
      Cost: 10000
      Currency: Vault
      FireworkToggle: true
      FireworkColors: 'White, Gray'
      Sound-Toggle: false
      Sound: 'BLOCK_ANVIL_PLACE'
    EnchOptions:
      SuccessPercent:
        Max: 15
        Min: 1
      DestroyPercent:
        Max: 95
        Min: 20
      MaxLvlToggle: true
      LvlRange:
        Max: 10
        Min: 1